data:
    dataset: "ArtPainting"
    dataset_name: str = "art_painting_v4"
    patch_size: 64
    channels: 3
    num_workers: 4
    data_dir: "../../"
    dataset_path: "../art_painting_data/train/image_old"
    mask_path: "../dtd/images"
    conditional: True
    n_subsets: 3
    class_names:
    - 'banded'
    - 'blotchy'
    - 'braided'
    - 'bubbly'
    - 'bumpy'
    image_size: 256

model:
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1, 2, 3, 4]
    num_res_blocks: 2
    attn_resolutions: [16, ]
    dropout: 0.0
    ema_rate: 0.999
    ema: True
    resamp_with_conv: True

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.01
    num_diffusion_timesteps: 1000

training:
    patch_n: 16
    batch_size: 1
    n_epochs: 1775
    n_iters: 2000000
    snapshot_freq: 10000
    validation_freq: 10000
    num_devices: 1
    precision: bf16-mixed
    accumulate_grad_batches: 1
    monitor: train_loss
    patience: 5

sampling:
    batch_size: 4
    last_only: True

optim:
    weight_decay: 0.000
    optimizer: "Adam"
    lr: 0.00002
    amsgrad: False
    eps: 0.00000001
